# .github/workflows/pages.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # (No build step needed for pure HTML/JS demo)
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Point at your site root — everything except the workflow itself
          path: |
            **/*
            !.github/**

  deploy:
    needs: build_and_upload
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
